### PR TITLE
Cleanup markdown

### PR DESCRIPTION
**Pull request by shntnu**

### CODE REVIEW

**Comment by ErinWeisbart** [comment]
I feel compelled to say that your "cleanup" of my markdown is a matter of personal preference ;)
You prefer expanded, I prefer compact.
You say po-tay-to, I say po-tah-to.

**Comment by shntnu** [comment]
Oops -- sorry for merging without review; I didn't want to interrupt your vacation 😀 

This was driven my trying to insert the data repo into the table and couldn't orient myself with the old formatting (found it too hard to navigate the columns in compact mode)

Any thoughts on that? Happy to revert that edit (the other cleanups were all markdown convention related)

**Comment by ErinWeisbart** [comment]
You're welcome to merge without my review!
How about we just continue changing the .md back and forth every time that either of us inserts anything into the table ;) 
In all seriousness, I'm fine with expanded.

**Comment by shntnu** [comment]
> You're welcome to merge without my review!
👍 

> How about we just continue changing the .md back and forth every time that either of us inserts anything into the table ;)

🥇 

> In all seriousness, I'm fine with expanded.

Sounds good, but I'm not wedded to it, in case we decide to revert at some point.

**Pull request merged**
