### PR TITLE
docs(readme): add link to the JUMP Hub

### PR DESCRIPTION
**Pull request by afermg**
When anyone is looking for JUMP information, we want to point towards our core resource central.

See https://broadinstitute.slack.com/archives/C024LG7T4P7/p1732629746748869?thread_ts=1732056358.091159&cid=C024LG7T4P7 for details.

### CODE REVIEW

**Comment by ErinWeisbart** [comment]
I would prefer that this was placed in the table in the "Associated Repositories" column. It can replace the "datasets" link that is currently there.

**Review by ErinWeisbart — APPROVED** [review]

**Comment by AnneCarpenter** [comment]
My only hesitation with that approach is I think JUMP Hub has info about more than just cpg0016? So shall we add it to all JUMP datasets (but Alán, perhaps it really is only about cpg0016 and also CPJUMP1 and no others?)

**Comment by afermg** [comment]
Mostly cpg0016, but it does contain some notes on CP JUMP 1.

**Comment by shntnu** [comment]
> So shall we add it to all JUMP datasets

I like this idea - the Hub includes resources that are fairly general, extending beyond cpg0016

**Comment by afermg** [comment]
Makes sense. I will open a new PR to add it to these columns:
image

**Pull request merged**
